### ISSUE TITLE
Create a database admin tool

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1002]
# Motivation

When running multiple shards per validators, based on a shared database (DynamoDb or ScyllaDb), there is currently no good way to initialize the database. Passing an argument `--create-if-missing` to the server of each shard creates a possible race condition.

# Solution

Create a db admin tool (or command) that can be called explicitly to initialize a (shared) database.

Not sure how the new tool should be named. We could abuse `linera-proxy` and add an option `--init-storage` there, but this feels wrong. Concretely, the README test would look like this:
```
for I in 1 2 3 4
do
    ./linera-db init --rm --storage xxx:shared_db_"$I"   #  <-- NEW `--rm` is inspired by `docker run`

    ./linera-proxy server_"$I".json &

    for J in $(seq 0 3)
    do
        ./linera-server run --storage xxx:shared_db_"$I" --server server_"$I".json --shard "$J" --genesis genesis.json &
    done
done
```

**Comment by MathieuDutSik** [comment]
This has been done via https://github.com/linera-io/linera-protocol/pull/1001
