### ISSUE TITLE
When I run publish-bytecode then create-application, I'll get wrong application ID returned to terminal

### ISSUE THREAD

**Issue by kikakkz** [linera-io/linera-protocol#1098]
Description:
When I run publish-bytecode then create-application, I'll get wrong application ID returned to terminal for some application.

Steps:
1  https://github.com/web3eye-io/res-peer/blob/6999e88c71c59dc39898eae84dfcfda807e53e70/deploy.sh#L45C1-L45C1 Here I deploy my application to local testnet

Result:
1  For the first 4 applications, I get right application ID returned to terminal
2  For the fifth application, I get wrong application ID which is different from the application list get from graphiql
In my test, I get the following value from terminal:
💙 Review application deployed
    Bytecode ID:    e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a650c0000000000000000000000
    Application ID: e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a650c0000000000000000000000e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a650e000000000000000`2`000000
But graphiql gives me
e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a650c0000000000000000000000e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a650e000000000000000`0`000000

**Comment by afck** [comment]
They might not be in the same order. If they've all been published and deployed on the same chain, their IDs will only differ in those last digits. Did none of the `create-application` calls return `…00000000` on the terminal?

**Comment by kikakkz** [comment]
> They might not be in the same order. If they've all been published and deployed on the same chain, their IDs will only differ in those last digits. Did none of the `create-application` calls return `…00000000` on the terminal?

only the last one has different output '...02000000', others're '...00000000'.

**Comment by kikakkz** [comment]
and i try to sleep 5 seconds between two create-application, the result is same.

**Comment by kikakkz** [comment]
and i think i can confirm every application i only deploy one time.

**Comment by afck** [comment]
Thanks! I have a suspicion that we're using the message ID index wrong somewhere. I'll look into it.
