### ISSUE TITLE
Simplify unrecoverable errors in Wasm

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1153]
* [x] Using Result for error handling makes sense for testability and together with async-awaits but most errors are not recoverable so the error values will be propagated all the way to the top-level. This costs fuel, so in theory errors could be lost at times (#1969).
* [x] We still have API returning an error-string on the service side. This is not consistent with the contract side (#1463).

**Comment by jvff** [comment]
The first sub-task depends on #1372.
