### ISSUE TITLE
Address the payment system in `execute_block`.

### ISSUE THREAD

**Issue by MathieuDutSik** [linera-io/linera-protocol#1187]
The failure scenario that we have is that if an account is credited but has a balance of zero, then it cannot process a transfer order since while the execution takes some fuel that could be paid back later. But the later is problematic to make work.

The current system in `execute_block` is to credit everything at the beginning, then do the operation and then at the end subtract the `credit`. The problem with that approach is that this is kind of overkill and mean that the execution would end only later while we could have ended it prematurely.

A better approached proposed by @afck is to do the following:
* Removing the `credit` entry.
* If the balance is `0` then the first operation has to be a transfer that covers the transfer fees.
* subtract the base fee for the block after the processing messages and operations.
* Remove the fee for storing incoming messages. Consider this to be included in the `message_price` on the sender chain.

**Comment by ma2bd** [comment]
> If the balance is 0 then the first operation has to be a transfer that covers the transfer fees.

To be clear, this one is just a guideline, not a rule to be enforced.

**Comment by MathieuDutSik** [comment]
This Issue has been addressed by PR 1226.
