### ISSUE TITLE
[GraphQL] Make sure collection keys in ChainState (inboxes, outboxes) are browsable for debugging

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1199]
We have a number of JSON scalar fields Origin, Target, and ChannelFullName that look tricky to guess from outside (unless I missed something).

**Comment by Twey** [comment]
After discussion with @christos-h and @ma2bd, my approach to this will be to:
- solve https://github.com/linera-io/linera-protocol/issues/678
- change the GraphQL representation of map views in general from
```map(key: Key!): Value!``
to
```
type MapFilters = {
  keys: [Key!]
}

type MapInput = {
  filter: MapFilters
}

type Map {
  value(key: Key!): Value
  values(input: MapInput): [Value!]! 
}
```

in which `map`/`Map` stands for the name of the map field, `Key` stands for the name of the map's key type, and `Value` stands for the name of the map's value type.

This allows querying multiple items without knowing their keys (by using a null value for `keys` in `MapFilters`), providing inspection support as required by this issue.  Additionally, it opens up as future work:
- extending `MapFilters` [with more sophisticated filtering predicates](https://www.apollographql.com/blog/graphql/filtering/how-to-search-and-filter-results-with-graphql/#filtering-for-items-matching-a-list) later on
- [paginating](https://relay.dev/graphql/connections.htm) the results of `values`, ideally using `async-graphql`'s built-in [pagination support](https://async-graphql.github.io/async-graphql/en/cursor_connections.html)

**Comment by Romainua** [comment]
great! Looking forward these!
