### ISSUE TITLE
When run linera-indexer, I get error 'invalid type: null, expected struct Event'

### ISSUE THREAD

**Issue by kikakkz** [linera-io/linera-protocol#1303]
**Description**
When run linera-indexer, I get error 'invalid type: null, expected struct Event'

**Steps**
1  Compile linera-indexer in linera-indexer/example
2  Run local test net with `linera net up`
3  Run node service with `linera service`
4  Run linera-indexer with `RUST_LOG=trace ./target/release/linera-indexer --storage /tmp/linera-indexer/indexer.db run --port 8088 --service-port 8081`

**Result**
We get error *Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("invalid type: null, expected struct Event", line: 1, column: 529) })*

**Commit**
f2310b4ab7fccc11108971b53368be09996e24ab

**Comment by Twey** [comment]
Hi @kikakkz, I'm working on some changes to the Linera GraphQL API at the moment so it's possible that the API has changed in ways that we need to match in the `linera-indexer`.

However, I'm having some trouble reproducing the error you describe.  If I do:

```console
$ eval "$(linera net helper)"
$ linera_spawn_and_read_wallet_variables linera net up
$ linera service &
$ linera-indexer --storage /tmp/linera-indexer/indexer.db run --port 8088 --service-port 8081
```

I get only successful output, and indeed I can connect to the GraphiQL instance exposed at `localhost:8088` and run queries like

```graphql
query {
  plugins
  state { chain, block, height }
}
```

which execute successfully.

Is there an additional step I need to take to see the error?

Alternatively, is it possible that you're mixing an older version of `linera` (e.g. in your `~/.cargo/bin`, from a previous `cargo install` command) with a newer version of `linera-indexer`?  Since the GraphQL API changed a bit in version `0.6`, `linera` from before then won't be compatible with `linera-indexer` built from a recent commit.

**Comment by kikakkz** [comment]
> Hi @kikakkz, I'm working on some changes to the Linera GraphQL API at the moment so it's possible that the API has changed in ways that we need to match in the `linera-indexer`.
> 
> However, I'm having some trouble reproducing the error you describe. If I do:
> 
> ```
> $ eval "$(linera net helper)"
> $ linera_spawn_and_read_wallet_variables linera net up
> $ linera service &
> $ linera-indexer --storage /tmp/linera-indexer/indexer.db run --port 8088 --service-port 8081
> ```
> 
> I get only successful output, and indeed I can connect to the GraphiQL instance exposed at `localhost:8088` and run queries like
> 
> ```graphql
> query {
>   plugins
>   state { chain, block, height }
> }
> ```
> 
> which execute successfully.
> 
> Is there an additional step I need to take to see the error?
> 
> Alternatively, is it possible that you're mixing an older version of `linera` (e.g. in your `~/.cargo/bin`, from a previous `cargo install` command) with a newer version of `linera-indexer`? Since the GraphQL API changed a bit in version `0.6`, `linera` from before then won't be compatible with `linera-indexer` built from a recent commit.

hey, @Twey , i didn't have additional step. i'll double test it today and update. and i think i run `cargo install --path linera-service` after checkout to v0.6.0. but please also let me double confirm again today, 😄

**Comment by kikakkz** [comment]
Hey @Twey , I test again

**Comment by kikakkz** [comment]
Hey @Twey , I test again

1  I run `cargo install --path linera-service` on tag v0.6.0
2  I check linera version with `linera --version`, and I get
![image](https://github.com/linera-io/linera-protocol/assets/13128505/eba75775-0bad-4521-8ddf-71b002a7fa98)
3  I run `linera net up` in terminal 1
4  I export environment with the output of step 3 in terminal 2
5  Then I run `linera service` in terminal 2
6  I check indexer version with `./target/release/linera-index --version` and i got
![image](https://github.com/linera-io/linera-protocol/assets/13128505/9fdb204b-33cc-4416-aee2-aff8847c97e0)
7  I run `./target/release/linera-indexer --storage /tmp/linera-indexer/indexer.db run --service-port 8081 --port 8088`
8  I get error `2023-12-01T01:16:22.353573Z  INFO linera_indexer::runner: config: IndexerConfig { client: RocksDbConfig { storage: "/tmp/linera-indexer/indexer.db", max_concurrent_queries: None, max_stream_queries: 10, cache_size: 1000 }, command: Run { listener: Listener { service: Service { service_port: 8081, service_address: "localhost", tls: false }, start: BlockHeight(0) }, port: 8088, chains: [] } }
Error: ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(8081), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) })`
![image](https://github.com/linera-io/linera-protocol/assets/13128505/932434ac-88c6-447c-8c61-530518d9dee8)

Could you please confirm my steps, too ?

**Comment by kikakkz** [comment]
@Twey oh, sorry. I think I use wrong port of service node. I'm stupid. sorry.

**Comment by Twey** [comment]
No worries, happens to us all! :grin:
