### ISSUE TITLE
Command to subscribe to other chains

### ISSUE THREAD

**Issue by Twey** [linera-io/linera-protocol#1342]
Currently the only way to subscribe to another chain is to submit a GraphQL mutation, but this is an important step in our distributed application deployment process so it should probably have a CLI command.

**Comment by afck** [comment]
To add some more detail:

The commands in [`linera.rs`](https://github.com/linera-io/linera-protocol/blob/main/linera-service/src/linera.rs) roughly mirror the queries and mutations in [`node_service.rs`](https://github.com/linera-io/linera-protocol/blob/main/linera-service/src/node_service.rs), but currently only the latter has a `subscribe` mutation.
A `Subscribe` command should be added to the former, to make it possible to subscribe to updates from another chain from the command line, too.
