### ISSUE TITLE
Resolve the issue of hash invalidation for `try_load_entry` of `ReentrantCollectionView`.

### ISSUE THREAD

**Issue by MathieuDutSik** [linera-io/linera-protocol#1442]
The functions `hash(&self)` and `try_load_entry(&self, short_key: Vec<u8>)` are both `&self` but the `try_load_entry` invalidates the hash since if an entry is missing then the try_load_entry will load it and set it to default. This makes a possibility that a hash is computed incorrectly and is neither the old nor the new hash.

We need the function `try_load_entry` to be `&self` because of GraphQL reasons.

Currently, we do not distinguish between a view loaded from an empty state to a view loaded from an existing one. But this could be achieved. If so, we could make the function `try_load_entry` really not modify the state. But that has to be considered carefully.

Checking if an entry exists cannot be done right now, because if an entry is cleared and saved then nothing is left on storage. And this is also true if the entries are deleted one by one. For all intent and purpose existing on storage is the same as being not default.

**Comment by ma2bd** [comment]
See my comment on #1443: https://github.com/linera-io/linera-protocol/pull/1443#discussion_r1443848417
