### ISSUE TITLE
Give an application ID to native tokens

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1472]
We'd like to represent native tokens as fungible application.

- [x] Make the fungible ABI part of the `linera-sdk`
- [ ] Decide if we create system APIs plus a Wasm application, or if we create the notion of native applications and implement the fungible ABI directly in Rust.

**Comment by andresilva91** [comment]
Deprioritized for now

**Comment by ma2bd** [comment]
I think you can close because it's solved in a way. Just the application ID is not standardized (everyone can define it)
