### ISSUE TITLE
Most client commands should only modify one chain.

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#1680]
E.g. currently changing the resource policy or adding or removing validators changes all owned chains, because it makes them receive the cross-chain message sent by the admin chain.

This should only be the case for commands that explicitly say so. It's probably sufficient to add a `sync-all` command (or an `--all-chains` option to the `sync` command).

**Comment by andresilva91** [comment]
Passing to @afck to check for outliers

**Comment by afck** [comment]
I went through the commands in `linera/main.rs` and couldn't find any that modify more than one chain.
