### ISSUE TITLE
Make application services longer lived

### ISSUE THREAD

**Issue by jvff** [linera-io/linera-protocol#1804]
# Motivation

Application services will likely have to handle multiple queries while the application's UI frontend is executing. It would in those cases be best to ensure that the Wasm instance is already running to answer those queries. It could also allow keep track of volatile "session state" in the service type, but this should be discussed some more.

# Proposal

Use a similar approach used for contracts, where the service type instance is stored in a global variable and reused for the queries.

**Comment by ma2bd** [comment]
As discussed, we're going to persist the last Wasm instance for each chain ID / application ID. Instances are destroyed if a new block extends the chain.
