### ISSUE TITLE
test_wasm_end_to_end_matching_engine::service_grpc is flaky

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1854]
Seen failing on the main branch:
```
thread 'test_wasm_end_to_end_matching_engine::service_grpc' panicked at linera-service/tests/end_to_end_tests.rs:59:13:
assertion `left == right` failed
  left: Amount(1000000000000000000)
 right: Amount(4000000000000000000)
```
https://github.com/linera-io/linera-protocol/actions/runs/8483991057/job/23246115005

**Comment by MathieuDutSik** [comment]
As I understand, this failure occurred rather randomly and is thus difficult to debug.

What could help in that respect is PR #1831. When run with `N_SIMULTANEOUS_VALIDATOR = 5` we can get pretty consistently by running `cargo test` the following error: ```
thread 'test_wasm_end_to_end_same_wallet_fungible::native_service_grpc' panicked at linera-service/tests/end_to_end_tests.rs:58:13:
assertion `left == right` failed
  left: Amount(0)
 right: Amount(5000000000000000000)
```

It might be the very same bug, and so it might provide a better entry point.
