### ISSUE TITLE
Refactor BlockProposal

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#1987]
The field `content: BlockAndRound` in `BlockProposal` was meant to be the part that the signature applies to. 

Now that we are adding oracles, we have to [make the block proposer _sign_ not only the block and round](https://github.com/linera-io/linera-protocol/blob/eb0c79aabaab5a6e973db51f66b18ee31a1b5361/linera-chain/src/data_types.rs#L795), but also the oracle records in the validated block, if it is included.
Otherwise, if there were already multiple rounds where the same proposed block got validated with different oracle values, someone who isn't the current round leader could take my proposal signature and swap out the validated block for a different one (same block, different oracle values) and make my round fail.

The block itself is currently duplicated, since it occurs both in `content` and in `validated`.

We could rename `BlockAndRound` to `ProposalContent` and add a field `outcome: Option<BlockExecutionOutcome>` (or even just `oracle_records: Option<Vec<OracleRecord>>`). We could then make `validated` a _lite_ certificate. A proposal would only be valid if `validated.is_some() == outcome.is_some()`, and if the lite certificate's hash matches the `CertificateValue::ValidatedBlock` resulting from combining the block with the outcome.

Alternatively, we could make the `block` in `BlockAndRound` an enum:

```rust
enum BlockOrCertificate {
    NewBlock(Block),
    ValidatedBlock(Certificate), // Must be `ValidatedBlock`.
}
```

**Comment by afck** [comment]
Related: https://github.com/linera-io/linera-protocol/issues/2113

**Comment by ma2bd** [comment]
Should we have different types of `Certificate`s? `serde-reflection` now supports templated data.

**Comment by afck** [comment]
Yes, I'd _love_ to make certificates type-safe, so that there is a type for "a certificate with a `ValidatedBlock` value". But that's a bigger issue than this one.
