### ISSUE TITLE
Support a connected mode in app services, so that multiple queries can modify a temporary state successively

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#1999]
Use cases:
* Allow successive AI queries to import the model to WASM only once.
* Allow splitting long answers into chunks (pagination)
* Allow splitting computationally expensive answers into a pseudo-stream

In the last case, ideally the WASM service instance would be allowed to keep computing ahead of the next query, but this is not strictly necessary.

**Comment by jvff** [comment]
Implemented through long-lived services in #2216
