### ISSUE TITLE
Consider explore having `OracleRecord` within `linera-execution`'s `OperationContext`

### ISSUE THREAD

**Issue by andresilva91** [linera-io/linera-protocol#2160]
Do same thing as `execution_state_actor`. So add the `OracleRecord` to `OperationContext`, and pass the context as mutable to `execute_operation`

**Comment by ma2bd** [comment]
@andresilva91 I'm not sure to see the point

**Comment by afck** [comment]
Right, this is probably obsolete after https://github.com/linera-io/linera-protocol/pull/2232.
