### ISSUE TITLE
Introduce the notion of root key in `KeyValueStore` APIs

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#2252]
# Motivation

In practice, all DB accesses caused by from a root view (e.g. `ChainStateView`) are contained in the key range prefixed by the `base_key` of the root view. Let’s call this a "root key".

Clearly, root keys are very good partitioning key for databases. In particular, the MemoryStore (for testing) and the ScyllaDbStore (for production, using [compound keys](https://university.scylladb.com/courses/data-modeling/lessons/basic-data-modeling-2/topic/primary-key-partition-key-clustering-key/)) could benefit from using root keys as partitioning keys.

# Proposal

* [ ] Split `Context::base_key` into `root_key` and `relative_key`
* [ ] Rename the first argument of `write_batch` to `root_key` (which it was already). Make the keys in the batch relative.
* [ ] Make all other read KeyValueStore APIs take a root key and otherwise only relative keys
* [ ] #2253
* [ ] #2254

**Comment by MathieuDutSik** [comment]
This has been implemented by #2348
