### ISSUE TITLE
Fungible Token example's web frontend doesn't support sending to applications

### ISSUE THREAD

**Issue by jvff** [linera-io/linera-protocol#2549]
# Motivation

In Linera, there are two types of accounts:

- User accounts protected by a secret and public key pair
- Application accounts protected by the protocol enforcing only that application's ID is able to do certain operations

https://github.com/linera-io/linera-protocol/blob/bd27e4297d9cc2e44fd4bca8c531d608b4f27c40/linera-base/src/identifiers.rs#L47-L52

The web interface for interacting with the Fungible Token example does not support sending tokens to an application's account.

# Proposal

Allow specifying a target account that starts with "Application:" and don't prepend "User:" to it when building the GraphQL query.

https://github.com/linera-io/linera-protocol/blob/bd27e4297d9cc2e44fd4bca8c531d608b4f27c40/examples/fungible/web-frontend/src/App.tsx#L100

**Comment by edwardluu** [comment]
Hi @jvff  Do you mean that this FE app can't transfer tokens from $OWNER_1 to $OWNER_2 with the same $APP_ID?

**Comment by jvff** [comment]
Hi! Not exactly, I tried to tweak the original description to be more clear. Let me know if it's still confusing.

**Comment by edwardluu** [comment]
Hi @jvff I have made a PR for this issue: https://github.com/linera-io/linera-protocol/pull/2587 
Please help me check it. If you want any updates please let me know.

**Comment by jvff** [comment]
Implemented by #2587
