### ISSUE TITLE
Change application graphql query to take only the application id

### ISSUE THREAD

**Issue by andresilva91** [linera-io/linera-protocol#2580]
Right now it takes the application id and the chain id, because a lot of tests want the application instance specific to a specific chain. We could instead create a test helper method for this, and make the actual application graphql query take only the application id (since now any chain has access to any application)

Original comment that triggered this issue creation: https://app.graphite.dev/github/pr/linera-io/linera-protocol/2426/Replace-ApplicationDescription-with-Blobs#comment-PRRC_kwDOGjZjtc5qcjCe

**Comment by ma2bd** [comment]
What query are we talking about here?

**Comment by andresilva91** [comment]
Discussed with @afck, we actually want this even not for tests, as it's useful to have the link back with the chain id everywhere
