### ISSUE TITLE
With v0.12.1, we get error `Unexpected response from validators` then chain client stuck

### ISSUE THREAD

**Issue by kikakkz** [linera-io/linera-protocol#2615]
**Description**
With v0.12.1, we get error `Unexpected response from validators` then chain client stuck. It's NOT reproducible with latest main branch. But I'm not able to get the root cause to know if it's already fixed, so I create this issue.

**Steps**
1  `git clone https://github.com/linera-io/linera-protocol.git`
2  `cd linera-protocol; git checkout v0.12.1; cargo install --path linera-service; cargo install --path linera-storage-service; cd -`
3  `git clone https://github.com/respeer-ai/res-peer.git`
4  Run local net and faucet with ResPeer applications with `cd res-peer; git checkout 7104c3a183273dbaa0a72a6759a220fd5a9b3c24; ./deploy-local.sh`
5  Open another terminal, then run `git clone https://github.com/linera-hacker/linera-dapps.git`
6  Modify IP in the linera-dapps/deploy-local.sh script to your PC IP for easy access, e.g. localhost or LAN ip
7  `cd linera-dapps; git checkout 93b3d5dcdb9fe57e18d4cf3f06310a33371a0173; ./deploy-local.sh`, it will claim 4 wallets from `http://localhost:8080` which is run in step 4
8 After several seconds, the mutation content will be printed in the terminal with its url to add liquidity
9 Open the url in the browser
10 Run mutation

**Result**
`Unexpected response from validators`

**Expected**
The block should be validated successfully.

**What I've done**
After some tracing of the error, I found with the same IncomingBundle, `linera-chain/rs/chain.rs: execute_block` may produce OutgoingMessage with different order in the array at client side and validator side. That may result in different hash.

**Screenshots**
![image](https://github.com/user-attachments/assets/93091373-2dd1-4213-9b21-7a000353ce56)

**NOTE**
It's only reproduced with **v0.12.1**. Till now I **DON'T** reproduce it with latest main commit fefa995f864cdcb3a101b2354c01077853afa421.

**Comment by kikakkz** [comment]
[client.log](https://github.com/user-attachments/files/17361482/client.log)
[validator.log](https://github.com/user-attachments/files/17361484/validator.log)

**Comment by kikakkz** [comment]
When we call mutation of addLiquidity, the contract will run https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L351, in which it will get the pool, or create a new one if it's not exists.

Currently we have to let pools on all chains have the same data, so we need to broadcast the AddLiquidity to creator chain, the the creator chain will publish to its subscribers.

**Comment by afck** [comment]
(There seem to be a few paths in these scripts that one either needs to change or create, e.g. `~/linera-project` and `/tmp/linera/dapps/`.)

**Comment by kikakkz** [comment]
> (There seem to be a few paths in these scripts that one either needs to change or create, e.g. `~/linera-project` ~and `/tmp/linera/dapps/`~. Edit: No, the latter was successfully created.)

Oh sorry, typo error `mkdir -l` :(, updated.

**Comment by afck** [comment]
Thank you! I've reproduced it on the `testnet_boole` branch.

**Comment by afck** [comment]
If I understand correctly, the problem seems to occur not when the `AddLiquidity` _operation_ is processed, but only later, when the resulting _message_ is handled, i.e. `on_msg_add_liquidity`?
https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L678

**Comment by afck** [comment]
So one of the outgoing messages here is probably the one from the ERC20 application:
https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L654

Not sure if the call to `mint` also sends a message?

And then there's `publish_message`:
https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L622
That seems to be the one that came first in the validators, but last in the client?

**Comment by kikakkz** [comment]
> If I understand correctly, the problem seems to occur not when the `AddLiquidity` _operation_ is processed, but only later, when the resulting _message_ is handled, i.e. `on_msg_add_liquidity`? https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L678

Yes. The operation seems is processed correctly. And when the message is published to creator chain, the error happen.

**Comment by kikakkz** [comment]
> So one of the outgoing messages here is probably the one from the ERC20 application: https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L654
> 
> Not sure if the call to `mint` also sends a message?
> 
> And then there's `publish_message`: https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L622 That seems to be the one that came first in the validators, but last in the client?

Mint also send a message. Currently we just publish every message to keep data be consistent on all chains to have a simple workable dex.

**Comment by kikakkz** [comment]
> So one of the outgoing messages here is probably the one from the ERC20 application: https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L654
> 
> Not sure if the call to `mint` also sends a message?
> 
> And then there's `publish_message`: https://github.com/linera-hacker/linera-dapps/blob/ebd6ff8fae385cc75e1149cbe8109b22dd27893c/swap/router/src/contract.rs#L622 That seems to be the one that came first in the validators, but last in the client?

Here publish_message is run by creator chain, which publish message to its subscribers.

**Comment by jvff** [comment]
Hi! Could you cherry-pick #2621 to see if it solves the issue?

Also wanted to use the opportunity to thank you very much for the detailed information! It helped _a lot_ when debugging the issue :heart:

**Comment by kikakkz** [comment]
> Hi! Could you cherry-pick #2621 to see if it solves the issue?
> 
> Also wanted to use the opportunity to thank you very much for the detailed information! It helped _a lot_ when debugging the issue ❤️

I test several times and seems it's not reproduced with v0.12.1 + commit 1c839b3b72ae0a268a0ee75251b17bd05693953f.
