### ISSUE TITLE
Audit codebase for other places we might need to check the ChainManager's pending blobs

### ISSUE THREAD

**Issue by andresilva91** [linera-io/linera-protocol#2717]
We had a bug because of this https://github.com/linera-io/linera-protocol/pull/2716
So let's check the rest of the codebase if there's other places we need to be checking this also

**Comment by afck** [comment]
Let's also make sure we clearly define where the blobs should be at which stage in the process.
* We need to have the blobs available where we need them to guarantee liveness. E.g. if I'm a client and I get the highest locked block from an honest validator, I also need to be able to get the blobs for that block from that validator. (Related: https://github.com/linera-io/linera-protocol/issues/2704)
* Avoid storing or caching blobs that we _don't_ need. E.g. a client shouldn't be able to make validators store blocks without paying for them, or put hundreds of blobs in their cache. (Related: https://github.com/linera-io/linera-protocol/issues/2173)
