### ISSUE TITLE
`u64` input parameters to `Node Service` is deserialized to `float`

### ISSUE THREAD

**Issue by kikakkz** [linera-io/linera-protocol#2743]
**Description**
We add an api here https://github.com/respeer-ai/linera-protocol/blob/1049478889b0c7ff7ba1a2c02075465a2a0eb505/linera-service/src/node_service.rs#L906 to let CheCko submit `ExecutedBlock` with its signature. But the `ExecutedBlock` cannot be deserialized correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/98873b33-ed13-455f-903b-4b1d58961f6a)
![image](https://github.com/user-attachments/assets/4977b67a-b53b-448f-97c1-d2e2913c0ea7)

**From @afck **
https://discord.com/channels/984941796272521226/1098657437965365289/1301122278268076052 `I think we'll need to serialize all integers greater than u32 as strings`

**Comment by kikakkz** [comment]
Hey, will this be fixed on testnet ? If it could be fixed we would like to deploy our applications to testnet, 😄

**Comment by ma2bd** [comment]
Yes we're on it!

**Comment by ma2bd** [comment]
Actually, the JSON standard supports u64. Can you try using a different JSON-parser in Javascript that supports large enums?

**Comment by kikakkz** [comment]
@jvff I create 3 test branches and 1 simple webui for easy reproduction of this issue.

Webui: https://github.com/kikakkz/linera-u64-serialization-webui.git
linera-protocol: https://github.com/respeer-ai/linera-protocol.git

I'm sorry I have to reproduce it with ResPeer fork of linera-protocol due to the code is a bit complicated of the whole process.

Branch serialize u64 as u64: test/serialize-u64-as-u64
Branch serialize u64 as string with `serde_with`: feat/serialize-u64-to-string
Branch merge `ResourceLimit` in PR #2888: hotfix/jvjv-fix-resource-control-policy-json-serialization-1

The following steps could reproduce and verify this issue with different branch (here I just list steps for branch `test/serialize-u64-as-u64`. Steps for other branch is totally same except the branch name):

- 1 `git clone https://github.com/respeer-ai/linera-protocol.git`
- 2 `cd linera-protocol`
- 3 `git checkout test/serialize-u64-as-u64`
- 4 `cargo install --path linera-service --features storage-service`
- 5 `cargo install --path linera-storage-service --features storage-service`
- 6 Run `linera net up` in terminal one
- 7 Run `linera faucet --port 40080 --amount "100.0" e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a65` in terminal two with `LINERA_WALLET` and `LINERA_STORAGE` output in step 6
- 8 Run `rm ~/.config/linera/wallet.* -rf` to clear old wallet
- 9 Run `linera wallet init --faucet http://localhost:40080` to create a new wallet from faucet, here we don't need to create a chain, chain will be created from frontend
- 10 Run `linera service --port 30080 --listener-skip-process-inbox` to serve the node in terminal three
- 11 `git clone https://github.com/kikakkz/linera-u64-serialization-webui.git`
- 12 `cd linera-u64-serialization-webui`
- 13 `yarn`
- 14 `yarn start`
- 15 At now it will open the test page in the browser. Each time refreshing the page, a new keypair will be generated.
![image](https://github.com/user-attachments/assets/11a31536-fa66-4c88-b35b-8f96b7928324)
- 16 `Node service url` is the url of service run in step 10, and `Faucet url` is the url of faucet run in step 7
- 17 Click `OPEN CHAIN` button to `claim` a new chain from faucet
- 18 Click `INITIALIZE WALLET WITH PUBLIC KEY` to initialize the chain store on the mentioned `Node Service` with public key only
- 19 Click `GET BLOCK MATERIAL` to get materials for a new block, including `pending messages`, `block round` and `local time`
- 20 Click `EXECUTE BLOCK` to let the `Node Service` execute the block

Something need to be noted here is:
- 1 We add a `block_material` function here https://github.com/respeer-ai/linera-protocol/blob/8bf9cb13156f470f2aa4ba7c54c494ace339d3ed/linera-service/src/node_service.rs#L1122 to get materials for new block
- 2 We add a `execute_block_with_full_materials` function here https://github.com/respeer-ai/linera-protocol/blob/8bf9cb13156f470f2aa4ba7c54c494ace339d3ed/linera-service/src/node_service.rs#L1001 to let `Node Service` construct a `ExecutedBlock`
- 3 We add a `wallet_init_without_keypair` function here https://github.com/respeer-ai/linera-protocol/blob/8bf9cb13156f470f2aa4ba7c54c494ace339d3ed/linera-service/src/node_service.rs#L830 to initialize microchain store on `Node Service` which could be managed with public key only

As the test result shown, with branch `feat/serialize-u64-to-string` and `hotfix/jvjv-fix-resource-control-policy-json-serialization-1`, we can execute block successfully.
![image](https://github.com/user-attachments/assets/6e978819-1239-4841-9842-d010db217e71)

And it failed with branch `test/serialize-u64-as-u64`:
![image](https://github.com/user-attachments/assets/e2720841-6499-4090-9a06-1a74e7089672)


BTW: all of the frontend code is in `https://github.com/kikakkz/linera-u64-serialization-webui/blob/master/src/pages/Index.vue` FYI.

**Comment by jvff** [comment]
Thanks for the excellent steps (again :smile:) to reproduce the issue!

After reproducing the issue, I learned that the issue is actually on the Javascript side. Basically it's rounding up the `u64::MAX` value to an `f64`, which then does not fit in an `u64` when it is sent back to Rust.

I believe the optimal solution would be to tweak the Javascript side to ensure JSON serialization keeps the numeric precision when needed. I opened a [PR](https://github.com/kikakkz/linera-u64-serialization-webui/pull/1) with an example fix.

Hope this helps!

**Comment by kikakkz** [comment]
> Thanks for the excellent steps (again 😄) to reproduce the issue!
> 
> After reproducing the issue, I learned that the issue is actually on the Javascript side. Basically it's rounding up the `u64::MAX` value to an `f64`, which then does not fit in an `u64` when it is sent back to Rust.
> 
> I believe the optimal solution would be to tweak the Javascript side to ensure JSON serialization keeps the numeric precision when needed. I opened a [PR](https://github.com/kikakkz/linera-u64-serialization-webui/pull/1) with an example fix.
> 
> Hope this helps!

Great! Great! Thanks to the reply. I'll test it soon.

**Comment by kikakkz** [comment]
> Thanks for the excellent steps (again 😄) to reproduce the issue!
> 
> After reproducing the issue, I learned that the issue is actually on the Javascript side. Basically it's rounding up the `u64::MAX` value to an `f64`, which then does not fit in an `u64` when it is sent back to Rust.
> 
> I believe the optimal solution would be to tweak the Javascript side to ensure JSON serialization keeps the numeric precision when needed. I opened a [PR](https://github.com/kikakkz/linera-u64-serialization-webui/pull/1) with an example fix.
> 
> Hope this helps!

I confirm with this solution we can execute and sign block in web client side then submit. Thanks a lot @jvff !
