### ISSUE TITLE
Stop the madness with the copy-pasted scales for Prometheus histogram vec

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#2795]
We have many instances of this vector in our codebase used for `prometheus_util::register_histogram_vec`:
```
[0.001, 0.002_5, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0, 500.0])
```

The copy-pasting is very suspicious. E.g. what happens if we want to optimize the values?
We should probably share those arrays and/or generate them based on some reasonable formula.

Also curious how Prometheus handles changed scales.

**Comment by andresilva91** [comment]
Prometheus defines a list of default buckets: https://docs.rs/prometheus/0.13.4/prometheus/constant.DEFAULT_BUCKETS.html
There are also functions to generate these buckets that we could play with: https://docs.rs/prometheus/0.13.4/prometheus/fn.exponential_buckets.html https://docs.rs/prometheus/0.13.4/prometheus/fn.linear_buckets.html

**Comment by MathieuDutSik** [comment]
This has been addressed by https://github.com/linera-io/linera-protocol/pull/2878
But maybe we could work further so that only one string is passed.
