### ISSUE TITLE
Explore caching crate dependencies in CI

### ISSUE THREAD

**Issue by ndr-ds** [linera-io/linera-protocol#2930]
We could explore using [rust-cache](https://github.com/marketplace/actions/rust-cache) for this

**Comment by Twey** [comment]
The [action](https://github.com/actions-rust-lang/setup-rust-toolchain) [we use](https://github.com/linera-io/linera-protocol/blob/2a97cdc7502459324c0cb1373f5c3136727cbaca/.github/workflows/rust.yml#L49C13-L49C54) already sets this up for us.

**Comment by ndr-ds** [comment]
Oh, nice! Good to know :) Will close this then
