### ISSUE TITLE
Executing a re-proposed block that uses an expired blob fails.

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#2993]
It must always be possible to re-propose the locked block, even if the committee that certified a blob which the new block reads has been deprecated in the meantime.

Let's send along the `ExecutionOutcome` with the proposal, so the validator doesn't have to execute it again until it is confirmed. (Alternatively, we could pass the provided blobs into `execute_block`, so they can be read even though they are not in storage.)

**Comment by deuszx** [comment]
This will have a negative effect on the latency. Probably also on a throughput.

**Comment by afck** [comment]
> This will have a negative effect on the latency.

We have to do one of the options to guarantee liveness. It will affect only the (hopefully rare) cases where rounds have failed in the first place, and then it is a tradeoff:
* Do we want to redundantly execute the block again?
* Or do we want to use more bandwidth but send along the execution outcome?

Regarding the blobs themselves, we could also consider adding back the blobs cache at some point.
