### ISSUE TITLE
Implement an atomic-swap application

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#305]
# Motivation

Linera should support DeFi applications, and having some initial examples implementing DeFi functionality can help with the development of the execution layer.

A simple DeFi application is being able to swap two different token types and amounts between two different users.

**Comment by afck** [comment]
# Proposal

As a first iteration, let's implement this as a new `atomic-swap` example application, with two `fungible` apps as dependencies.

Let's say Alice wants to sell 1 FOO for 2 BAR tokens to Bob.
* She creates or registers `atomic-swap` on her chain A and makes a `Swap(1, 2)` operation.
* The `atomic-swap` app then creates a new chain S, with the following configuration:
  * No super owners; only Alice and Bob as regular owners.
  * A few multi-leader rounds, then single leader, so normally both can make blocks, but nobody can stall the chain indefinitely.
  * Only `atomic-swap` and `fungible` messages and operations are allowed (apart from the `OpenChain` message).
  * Every block must contain an `atomic-swap` operation.
  * `atomic-swap` is allowed to close the chain.
* The app also transfers 1 FOO from Alice's account on A to the `atomic-swap` app's account on S, and sends a `Swap(1, 2)` message from A to S.
* At any time Bob or Alice can make a block on S with a `Cancel` operation. That will send all FOOs and BARs back, and close S.
* At any time Bob and Alice can make a block on S with an `Execute` operation. That will check that there are exactly 1 FOO and 2 BAR on the chain, send the BARs to Alice and the FOOs to Bob, and close S. (If `Execute` happens before the incoming `Swap` message, it fails.)

# Core protocol requirements

- [ ] Applications can create new chains.
- [ ] Applications can close the current chain. (If explicitly allowed in the chain config.)
- [ ] Chains can be configured to only allow messages and operations from certain applications.
- [ ] Chains can be configured to only allow blocks containing at least one message or operation from a particular application.
- [ ] Remaining incoming messages are automatically bounced when a chain is closed.

# Possible extensions

* We could forbid `Cancel` before some deadline, so Bob knows he can complete the swap if he does it before the deadline.
* We could forbid `Execute` _after_ the deadline, so after that it can only be `Cancel`ed.
* We could make the fallback owners (once that's implemented) `Cancel` the swap automatically, so Alice and Bob don't even have to do anything.

**Comment by afck** [comment]
As discussed, we should generalize this and make it work like (or integrate it into) the `matching-engine`.

**Comment by afck** [comment]
> Chains can be configured to only allow messages and operations from certain applications.

Maybe a more general (?) alternative: Chains can be configured to always contain a particular _last_ operation in each block.

In this operation the contract can decide whether its state changed as expected, and fail if it didn't.

**Comment by afck** [comment]
As discussed, we will extend the Matching Engine example instead of implementing a new atomic swap application. This requires a few modifications:

* A convenient way to set up a new multi-owner chain where the matching engine is the authorized application for operations and closing the chain.
* A `CloseChain` operation that cancels all orders and closes the chain.
* Atomic message bundles, so that with each transfer, the corresponding order is also handled.

**Comment by afck** [comment]
The order book always resides on the application's creator chain. So to set up an atomic swap chain, we need to:
* Create a new chain.
* Create a Matching Engine application on that chain.
* Change the application permissions.
