### ISSUE TITLE
Implement an order book application

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#306]
# Motivation

Linera should support DeFi applications, and having some initial examples implementing DeFi functionality can help with the development of the execution layer.

An order book application can serve as a more complex DeFi application.

**Comment by MathieuDutSik** [comment]
The issue has been addressed by the PR https://github.com/linera-io/linera-protocol/pull/662
Further improvements are possible, but we can consider it resolved for the time being.
