### ISSUE TITLE
Make it possible for user chains to "join" applications

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#309]
# Motivation

Micro-chains can only execute user application operations if it has received an effect for the application it wants to use (or if the application was initially created on that micro-chain). It should be possible for users to request one or more public "application registration chains" to receive an empty effect from a desired application so that it is deployed on the requested micro-chain.

**Comment by ma2bd** [comment]
We need system support for a "ping" command

**Comment by afck** [comment]
So we'd:
* add a `PingApplication(UserApplicationId)` variant to `SystemOperation`,
* a `PingApplication(UserApplicationId)` variant to `SystemEffect`,
* and `fn execute_ping(&self, context: &EffectContext) -> Result<ExecutionResult, Self::Error>` to `Contract`?

Or should we just call `execute_effect` with an empty effect?

**Comment by afck** [comment]
Done in https://github.com/linera-io/linera-protocol/pull/726.
