### ISSUE TITLE
Save and restore application state between cross-application calls

### ISSUE THREAD

**Issue by jvff** [linera-io/linera-protocol#487]
# Motivation

Linera applications currently operate in an actor-model like execution model. Every operation, effect, cross-application call, etc. use a new application runtime specific for handling that request. However, that means that if an application calls another, and the other application calls back to the first application, there will be two separate execution runtimes for the first application, possibly with different states.

# Proposed Solution

As an initial fix, store the application state before calling the other application, and reload after the call is finished. That way, if the other application calls back, the new runtime will load the updated state.

One problem with this solution is that `View::abort` on the application's state will behave differently after calling another application, so this information should be documented.

To save and restore the state, a method should be added to the application state type, using the `linera_sdk::contract!` macro, adding something like:

```rust
impl $application {
    pub fn call_other_application(&mut self, application: ApplicationId, argument: &[u8]) -> Vec<u8> {
        self.write_batch();
        let result = system_api::try_call_application(application, argument);
        *self = Self::load();
        result
    }
}
```

**Comment by sshbgnv** [comment]
ok
