### ISSUE TITLE
Don't read values from storage twice just to check existence

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#515]
In `check_no_missing_bytecode` we currently fully read from storage all the bytecode just to check whether we have it in storage.

We should only find out whether the entry exists, without reading all the content.

**Comment by MathieuDutSik** [comment]
For that purpose, would it help to provide a function in the `KeyValueStoreClient` that checks if a variable is present?
That could be faster than downloading it in some cases.

**Comment by afck** [comment]
Yes, it would just return `true` if an entry with a given key exists. :+1:
