### ISSUE TITLE
Create a `cargo-linera` tool

### ISSUE THREAD

**Issue by jvff** [linera-io/linera-protocol#566]
# Motivation

Linera applications written in Rust are becoming non-trivial, because they require two WebAssembly binaries (the contract and the service), and because unit tests need special configuration to run correctly while integration tests must be compiled for the host target. These details might be hard for newcomers to grasp, so anything that helps with the mental load should ease adoption.

# Proposed Solution

In Rust, it's not uncommon to write Cargo CLI extensions to automate part of that. Therefore, we could write a `cargo-linera` extension. Initially, it could have the following features:

- `cargo linera new`: sets up a new application project structure, with a common state module, and two WebAssembly binaries.
- `cargo linera test`: runs the unit tests in WebAssembly using a custom test runner, and runs the integration tests on the host target.

**Comment by christos-h** [comment]
Closed by #640 .
