### ISSUE TITLE
Define a trait `GraphQLView` and make `#[derive(GraphQLView)]` generate a trait implementation for one container at a time

### ISSUE THREAD

**Issue by MathieuDutSik** [linera-io/linera-protocol#678]
Currently, the `GraphQLView` does not work recursively (to be fair, like other traits).
The problem occurs with the following example:
```rust
#[derive(RootView, GraphQLView)]
pub struct Counter<C> {
    pub value: CollectionView<C, u64, RegisterView<C, u64>>,
}
```

But actually the following will work
```rust
#[derive(View, GraphQLView)]
pub struct ContainerView<C> {
  pub intro_val: RegisterView<C,u64>,
}

#[derive(RootView, GraphQLView)]
pub struct Counter<C> {
    pub value: CollectionView<C, u64, ContainerView<C>>,
}
```

So, we have a reasonable solution to a common problem. But do we consider it an acceptable solution?

**Comment by ma2bd** [comment]
Let me think about this. Part of the problem is that there is no such trait as `GraphQLView` yet.

**Comment by ma2bd** [comment]
We might be able to implement `async_graphql::OutputType` directly for all basic view constructions (register, etc) and `async_graphql::ObjectType` for some of them (like maps and collections). Then:
* `GraphQLView` would be defined as `pub trait GraphQLView: View + async_graphql::ObjectType {}`
* `#[derive(GraphQLView)]` would only concert user-defined views.
