### ISSUE TITLE
Improve asynchronicity of the protocol code

### ISSUE THREAD

**Issue by MathieuDutSik** [linera-io/linera-protocol#685]
We want to avoid the `chain.rs` asynchronous code inside of the loop which makes some operation slower than they should be. This is not because of parallelism but because of the concurrency. Parallelism is not something we exclude, but the limitation by back and forth path is the problem to address first.

Example:
```rust
        let outbox_counters = self.outbox_counters.get_mut();
        for recipient in recipients {
            let target = Target::chain(recipient);
            let outbox = self.outboxes.load_entry_mut(&target).await?;
            if outbox.schedule_message(height)? {
                *outbox_counters.entry(height).or_default() += 1;
            }
        }
```
It is possible to improve looks highly improvable with respect to speed by having a `load_multi_entry_mut` that loads several entries at once.

This should be the model of code to optimize out. There are also more complicated multiple loops but they should operate similarly.

**Comment by ma2bd** [comment]
Async streams may come handy in some cases: https://gendignoux.com/blog/2021/04/01/rust-async-streams-futures-part1.html

**Comment by MathieuDutSik** [comment]
I believe that the protocol has been significantly improved with respect to the async calls by using `try_load_entries_mut` and similar and that the issue can be considered resolved.
It is possible that there are still some issues, but we would have to create separate issues for that.
