### ISSUE TITLE
Improve chain listener

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#687]
- [x] Support network disconnections
- [x] Support reconfigurations
- [x] Do not call `synchronize_from_validators`
- [x] Move synchronization logic to `linera-core`
- [x] Skip redundant notifications before synchronization

Probably out of scope for now:
- [ ] Resist DoS from rogue validators

**Comment by afck** [comment]
> Support network disconnections

Part of this could be to retry inside the stream returned by `GrpcClient::subscribe`, depending on the status code, and possibly with some delays (exponential backoff or something). The downside is that the returned stream could now silently skip notifications that were sent while it was reconnecting.

The other status codes would probably terminate the stream.

An alternative is to make the `NotificationStream` type not `Notification` but `Result<Notification, Status>`, with our own `Status` enum, and handle the different cases in the chain listener.

**Comment by afck** [comment]
Closed, and turned the last point into its own issue.
