### ISSUE TITLE
Migrate WalletState to View + Rocksdb

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#712]
We're currently saving the entire `WalletState` every time we have modified a `UserChain`.
It seems like we should just migrate to `linera-views`.
```
#[derive(RootView)]
pub struct WalletState<C> {
    chains: MapView<C, ChainId, UserChain>,
    unassigned_key_pairs: MapView<C, PublicKey, KeyPair>,
    default_chain_id: RegisterView<C, Option<ChainId>>,
    genesis_config: RegisterView<C, GenesisConfig>,
}
```

On the down side, developers will want to explore the `WalletState` for debugging. My preferred solution is to set up a GraphQL service (also using derive macros as we do for on-chain data).

**Comment by christos-h** [comment]
This implies two separate files, i.e. `storage.db` *and* `wallet.db`.
