### ISSUE TITLE
Make new applications discoverable

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#718]
Some applications (crowd-funding, auctions) are meant to be joined by arbitrary users.

Currently, the only way for a user chain to "join" an app is by being (implicitly) "invited" in a direct message from a chain already having the app.

There should be some support in the system
(1) to broadcast app invitations to subscribers,
(2) to request an app invitation when someone know the app id from an external source.

Both behaviors could be configured when the app is created.

**Comment by afck** [comment]
I'm not sure about (1): Is it really a common use case that someone is interested in all applications published on a particular chain? I'd rather expect that in almost all cases the user needs to know the application ID in advance anyway.

Regarding (2) the main question is from which point on application-specific user data should be supported:
* **Always**: The invitation _request_ already contains an application-specific payload (any effect?), based on which the application can decide whether to invite the user or not. This is the most flexible option, but it would probably require querying the application service on the _creator_ chain (or somehow the bytecode directly) to create the payload.
* **Only invitation**: The request only contains the application ID, but the invitation itself could already be a user application effect, with payload. This would involve a new method in the contract API to handle the invitation request.
* **Never**: The invitation simply registers the application on the other chain. The invited user then has to start using it by executing an operation. This is the simplest option, but doesn't allow the application to decide case-by-case whether to send an invitation.

**Comment by afck** [comment]
As discussed, we implement the "**Never**" option for now, i.e. there is a `RequestApplication(UserApplicationId)` system effect that is always answered by `RegisterApplications` with the requested application and all its dependencies.

In the long run, when we have reactive channels, there could be a system channel where all applications are announced. The requester could then immediately register the new application, without having to wait for the creator chain to process the request.

**Comment by afck** [comment]
With https://github.com/linera-io/linera-protocol/issues/2167 invitations and registration requests will be obsolete.

Not sure a channel where all new applications are announced would be useful. Should we close this?
