### ISSUE TITLE
Error handling vs panicking in WIT conversions

### ISSUE THREAD

**Issue by christos-h** [linera-io/linera-protocol#743]
The introduction of associated types in `linera_sdk::Contract` and `linera_sdk::Service` performs serde behind the scenes for users. 

Since the serde APIs are fallible, we need to understand if serde can indeed fail in these circumstances and manage the errors appropriately instead of panicking.

**Comment by jvff** [comment]
Based on some recent discussions, the goal is to replace returning errors (which are currently converted to strings) with panicking. This simplifies the interfaces.

**Comment by jvff** [comment]
Implemented by #1969.
