### ISSUE TITLE
Support Wasm in AWS-based storage

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#763]
DynamoDb currently fails because certificates containing bytecode are (almost always) larger than 400kb.

* One quick fix would be to split large certificates across several keys
* Another option would be to use S3 instead of DynamoDb for large blobs (this may be slow)

**Comment by ma2bd** [comment]
https://aws.amazon.com/blogs/database/large-object-storage-strategies-for-amazon-dynamodb/

**Comment by MathieuDutSik** [comment]
That issue has been addressed by:
* PR #972 that implements a workaround to the problem and removes the `#[ignore]` statements.
* PR #967 that puts the failing tests as `#[ignore]` and puts the Value Splitting for DynamoDb.
* PR #862 that introduces a module for splitting value into smaller ones.
* PR #848 that puts advanced tests for the `KeyValueStoreClient`.
