### ISSUE TITLE
Implement the derived traits manually for ApplicationId, SessionId, BytecodeId

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#768]
Sadly, adding a phantom type in the middle ruins everywhere if the parameters doesn't implement the traits. Since the parameters is user-facing, we'd rather avoid the extra burden.

Note: This was done already for `Clone` and `Copy` as in this example:
```
// Cannot use #[derive(Clone)] because it requires `A: Copy`.
impl<A> Clone for SessionId<A> {
    fn clone(&self) -> Self {
        Self {
            application_id: self.application_id,
            index: self.index,
        }
    }
}

impl<A> Copy for SessionId<A> {}
```

Extra context: https://github.com/rust-lang/rust/issues/26925

**Comment by afck** [comment]
Re-opening:
* `Serialize` and `Deserialize` are not done yet.
* The `derive` attributes on the contract ABIs should now be removed, together with the TODOs.
