### ISSUE TITLE
func transfer problem

### ISSUE THREAD

**Issue by firedpeanut** [linera-io/linera-protocol#798]
compare:  transfer_to_account_unsafe_unconfirmed, transfer
transfer_to_account_unsafe_unconfirmed is more prepare_chain() than  transfer
Is transfer_to_account_unsafe_unconfirmed better?
https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L1512
https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L1080-L1084

https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L1214
https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L896-L915

**Comment by ma2bd** [comment]
I don't quite understand the question

**Comment by firedpeanut** [comment]
add  fun prepare_chain() in  transfer

**Comment by ma2bd** [comment]
Indeed. Thanks for the report!
