### ISSUE TITLE
code format

### ISSUE THREAD

**Issue by firedpeanut** [linera-io/linera-protocol#799]
fn communicate_chain_updates
https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L608-L609 vs
https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L623

https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L611-L614 vs
https://github.com/linera-io/linera-protocol/blob/64f76baa97af45816203decce236e6741c4ce933/linera-core/src/client.rs#L625 difficult difficult to read

**Comment by ma2bd** [comment]
Hi @firedpeanut Thanks for the feedback. These examples don't go against our current coding guidelines, so I'm going to close the issue.
