### ISSUE TITLE
endless loop?

### ISSUE THREAD

**Issue by firedpeanut** [linera-io/linera-protocol#805]
https://github.com/linera-io/linera-protocol/blob/26b9090018f5709f7746235892795023191ad6ca/linera-core/src/worker.rs#L310
https://github.com/linera-io/linera-protocol/blob/26b9090018f5709f7746235892795023191ad6ca/linera-core/src/worker.rs#L308-L314

**Comment by firedpeanut** [comment]
Line 308 CrossChainRequest::UpdateRecipient
Line 310 CrossChainRequest::ConfirmUpdatedRecipient

**Comment by afck** [comment]
Yes, and then when `ConfirmUpdatedRecipient` pops out in line 308, there will be no additional requests added in line 310.

**Comment by firedpeanut** [comment]
I see
It's better not to write like this
Should open another while

**Comment by firedpeanut** [comment]
now see fun handle_cross_chain_request. so I see.

**Comment by afck** [comment]
Not sure about another `while` loop: An `UpdateRecipient` in the second loop would then need to be treated as a programming error. But maybe we could even make it type safe and split `handle_cross_chain_request` into two methods, one for handling `UpdateRecipient` and one for `ConfirmeUpdatedRecipient`; the latter wouldn't return any requests. Not sure if it's worth the more complicated code, though.

**Comment by firedpeanut** [comment]
let mut requests = VecDeque::from(actions.cross_chain_requests);
+        let mut request1 = VecDeque::new();
         while let Some(request) = requests.pop_front() {
             let actions = self.handle_cross_chain_request(request).await?;
-            requests.extend(actions.cross_chain_requests);
+            request1.extend(actions.cross_chain_requests);
+            if let Some(notifications) = notifications.as_mut() {
+                notifications.extend(actions.notifications);
+            }
+        }
+        while let Some(request) = request1.pop_front() {
+            let actions = self.handle_cross_chain_request(request).await?;
             if let Some(notifications) = notifications.as_mut() {
                 notifications.extend(actions.notifications);
             }

**Comment by afck** [comment]
Sure, I'm not against it. But that's what I mean: In the second loop `actions.cross_chain_requests` is expected to be always empty, so I'd prefer to make that statically clear, and split up `handle_cross_chain_requests` into two methods. The second one, called in the second loop, would only handle `ConfirmedUpdatedRecipient` messages and not have a return value with cross-chain requests.

Anyway, I don't feel strongly about this. I'll let others chime in.

**Comment by ma2bd** [comment]
For context, in previous versions of the code, `UpdateRecipient` could create more `UpdateRecipient` messages. This was indeed a bit dangerous for termination (and network health on the validator side) but not necessarily bad: we may have to bring back some version of this for #366.
