### ISSUE TITLE
Error: run_local.sh

### ISSUE THREAD

**Issue by firedpeanut** [linera-io/linera-protocol#813]
./linera --wallet wallet.json open-chain --to-public-key 809535908c8628aaf16a1a78ea885366d40cd799f7992906ff1149b6ec03fac0
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No key available to interact with single-owner chain e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a65', linera-service/src/linera.rs:957:67
https://linera.dev/getting_started/hello_linera.html
error:
https://github.com/linera-io/linera-protocol/blob/dc58afae6b779ec5d167a7a40f949dcb41bca4ec/scripts/run_local.sh#L60
https://github.com/linera-io/linera-protocol/blob/dc58afae6b779ec5d167a7a40f949dcb41bca4ec/linera-core/src/client.rs#L1106
https://github.com/linera-io/linera-protocol/blob/dc58afae6b779ec5d167a7a40f949dcb41bca4ec/linera-core/src/client.rs#L325

**Comment by firedpeanut** [comment]
@ma2bd please solve this problem quickly

**Comment by afck** [comment]
Thank you for reporting this! Could you try out whether https://github.com/linera-io/linera-protocol/pull/814 fixes it?
