### ISSUE TITLE
Got an error on installing linera locally (I'm using Windows)

### ISSUE THREAD

**Issue by ryjin111** [linera-io/linera-protocol#816]
error: failed to run custom build command for `linera-rpc v0.1.0 (C:\Users\Administrator\Documents\GitHub\linera-protocol\linera-rpc)`

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\Documents\GitHub\linera-protocol\target\release\build\linera-rpc-034e06437a3697e3\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=proto/rpc.proto

  --- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\prost-build-0.11.9\src\lib.rs:1457:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `file-lock v2.1.9`

Caused by:
  process didn't exit successfully: `C:\Users\Administrator\Documents\GitHub\linera-protocol\target\release\build\file-lock-44b7b006f2cd399b\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  running: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Z7" "-Brepro" "-W4" "-FoC:\\Users\\Administrator\\Documents\\GitHub\\linera-protocol\\target\\release\\build\\file-lock-eca789900825de87\\out\\src/file_lock.o" "-c" "src/file_lock.c"
  file_lock.c
  src/file_lock.c(9): error C2079: 'fl' uses undefined struct 'flock'
  src/file_lock.c(11): error C2224: left of '.l_type' must have struct/union type
  src/file_lock.c(11): error C2065: 'F_WRLCK': undeclared identifier
  src/file_lock.c(11): error C2065: 'F_RDLCK': undeclared identifier
  src/file_lock.c(12): error C2224: left of '.l_whence' must have struct/union type
  src/file_lock.c(12): error C2065: 'SEEK_SET': undeclared identifier
  src/file_lock.c(13): error C2224: left of '.l_start' must have struct/union type
  src/file_lock.c(14): error C2224: left of '.l_len' must have struct/union type
  src/file_lock.c(16): warning C4013: 'fcntl' undefined; assuming extern returning int
  src/file_lock.c(16): error C2065: 'F_SETLKW': undeclared identifier
  src/file_lock.c(16): error C2065: 'F_SETLK': undeclared identifier
  src/file_lock.c(24): error C2079: 'fl' uses undefined struct 'flock'
  src/file_lock.c(30): error C2224: left of '.l_type' must have struct/union type
  src/file_lock.c(30): error C2065: 'F_UNLCK': undeclared identifier
  src/file_lock.c(31): error C2224: left of '.l_whence' must have struct/union type
  src/file_lock.c(31): error C2065: 'SEEK_SET': undeclared identifier
  src/file_lock.c(32): error C2224: left of '.l_start' must have struct/union type
  src/file_lock.c(33): error C2224: left of '.l_len' must have struct/union type
  src/file_lock.c(35): error C2065: 'F_SETLK': undeclared identifier
  exit code: 2

  --- stderr

  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Z7" "-Brepro" "-W4" "-FoC:\\Users\\Administrator\\Documents\\GitHub\\linera-protocol\\target\\release\\build\\file-lock-eca789900825de87\\out\\src/file_lock.o" "-c" "src/file_lock.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

error: failed to compile `linera-service v0.1.0 (C:\Users\Administrator\Documents\GitHub\linera-protocol\linera-service)`, intermediate artifacts can be found at `C:\Users\Administrator\Documents\GitHub\linera-protocol\target`

**Comment by afck** [comment]
Thank you for reporting this!
Windows is currently untested on our side, so we can't promise to resolve this right now, but it looks like you haven't installed the Protocol Buffers compiler?

> If protoc is installed and this crate had trouble finding it, you can set the PROTOC environment variable with the specific path to your installed protoc binary. You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.
>
> For more information: https://docs.rs/prost-build/#sourcing-protoc

**Comment by ryjin111** [comment]
> 

Thanks for the reply i've finished installing the protoc and still there a lot of things to install

libsrocksdb
file-lock

**Comment by afck** [comment]
Linera uses [rust-rocksdb](https://crates.io/crates/rocksdb) as a dependency. Could you try out whether you can compile that crate? They seem to have a few [open tickets](https://github.com/rust-rocksdb/rust-rocksdb/issues) related to Windows or Visual Studio; maybe it's related to [this one](https://www.github.com/rust-rocksdb/rust-rocksdb/issues/381#issuecomment-630415506)?

**Comment by afck** [comment]
Our dependency is currently version 0.19.0 of rust-rocksdb. If you can compile the current version, you could try changing the dependency in `linera-protocol`'s top-level `Cargo.toml` to `rocksdb = "0.21.0"`.

**Comment by ryjin111** [comment]
> Our dependency is currently version 0.19.0 of rust-rocksdb. If you can compile the current version, you could try changing the dependency in `linera-protocol`'s top-level `Cargo.toml` to `rocksdb = "0.21.0"`.

still the same it seems windows is still not compatible atm
