### ISSUE TITLE
When run 'linera --wallet $LINERA_WALLET --storage $LINERA_STORAGE service' at the same machine, 'linera --storage $LINERA_STORAGE --wallet $LINERA_WALLET wallet show' will be error with 'Error getting write lock to wallet'

### ISSUE THREAD

**Issue by kikakkz** [linera-io/linera-protocol#818]
**Issue**:
When run 'linera --wallet $LINERA_WALLET --storage $LINERA_STORAGE service' at the same machine, 'linera --storage $LINERA_STORAGE --wallet $LINERA_WALLET wallet show' will be error with 'Error getting write lock to wallet'

**Steps**:
1  Run ./script/run_local.sh in terminal 1
2  Run `linera --wallet $LINERA_WALLET --storage $LINERA_STORAGE service` with right environment set in terminal 2 in the same machine as 1
3  Run `linera --storage $LINERA_STORAGE --wallet $LINERA_WALLET wallet show` in terminal 3 in the same machine as 1

**Expectation**:
`linera --storage $LINERA_STORAGE --wallet $LINERA_WALLET wallet show` should display result successfully

**Result**:
We get error: `Error getting write lock to wallet: Resource temporarily unavailable (os error 11)`. Things will be OK after we stop command run in 2.

**Screenshot**:
![image](https://github.com/linera-io/linera-protocol/assets/13128505/4ffc2224-7c48-4ac4-a4ce-7dd9dc1e0d4a)

**Comment by kikakkz** [comment]
`8d2ad58366e780f2667bbc572684ea8f409d1544` add test commit

**Comment by afck** [comment]
That's by design, at least for now: The node service needs exclusive access to the wallet.

While it is running, you can retrieve information about a chain using the `chain` query via the [GraphiQL IDE](https://linera.dev/core_concepts/node_service.html#graphiql-ide).

**Comment by kikakkz** [comment]
> That's by design, at least for now: The node service needs exclusive access to the wallet.
> 
> While it is running, you can retrieve information about a chain using the `chain` query via the [GraphiQL IDE](https://linera.dev/core_concepts/node_service.html#graphiql-ide).

understand.
