### ISSUE TITLE
In `create_application` avoid using the String and string replacement

### ISSUE THREAD

**Issue by MathieuDutSik** [linera-io/linera-protocol#828]
This is relevant to the `end_to_end_tests.rs` where we are forced to replace " by \" in order that when the string is printed, the graphQL request passes correctly.
Not clear what could be the solution since graphQL is inherently text protocol and not strongly typed.

**Comment by ma2bd** [comment]
> Not clear what could be the solution since graphQL is inherently text protocol and not strongly typed.

That's why we introduced the concept of ABI.
