### ISSUE TITLE
Ensure Wasm guest errors are propagated correctly

### ISSUE THREAD

**Issue by jvff** [linera-io/linera-protocol#907]
# Motivation

The `ExecutionError::UserError` is an error variant representing errors created by users. They should only be created if the application code returns an error from one of the entrypoint functions or if the user explicitly panics.

# Proposed Solution

Write tests that ensure that on both runtimes (Wasmer and Wasmtime):

- Returning an `Err(_)` from the guest creates a `UserError` in the host
- `panic`king from the guest creates a `UserError` in the host
- It's possible to abort execution from a host function called by the guest, and that the error used to abort execution does **NOT** become a `UserError` at the end of the execution
- Accessing an invalid memory address in the guest leads to a `UserError` (or maybe not?)
- (Other possible trap conditions should be checked as well)

Any test that fail on `main` should include fixes to the code.

**Comment by ma2bd** [comment]
Not sure if this matters as much after #1398
