### ISSUE TITLE
The chain listener should ignore invalid notifications.

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#916]
If the chain listener loop returns an error, it effectively stops its subscription for the whole chain, to all validators. A bogus notification can also set the block height in the tracker to a wrong value and cause the listener to ignore legitimate notifications from other validators.

**Comment by ma2bd** [comment]
Not entirely sure that disconnecting is best

**Comment by afck** [comment]
OK, I guess there's two kinds of errors: Ones that could be a temporary outage (failing to provide a block) and ones that are definitely a malfunction, like claiming that the `NewBlock` is a `ValidatedBlock` instead of `ConfirmedBlock`.

Maybe for the former we should just ignore the notification. But in the latter case, I don't think it makes sense to accept anything else that that validator sends?

**Comment by ma2bd** [comment]
@afck I believe this is resolved (in the current state of the title)?

**Comment by afck** [comment]
Right, I forgot to close it when https://github.com/linera-io/linera-protocol/pull/939 got merged.
