### ISSUE TITLE
Index the number of incoming messages, operations, and outgoing messages in the chain state

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#927]
Motivation: make performance measurement easier

Proposal:
* Add three `u32` fields to the struct `ChainStateView::tip_state` (say `num_incoming_messages`, `num_operations`, `num_outgoing_messages`) counting the respective numbers of incoming messages, operations, and outgoing messages that were processed (or created) by the chain until now.
* In `worker.rs / process_confirmed_block`, when `tip_state` is updated at the end, increment each counter by the right amount (`block.incoming_messages.len()`, `block.operations.len()`, `messages.len()`)
~~* (TBD) Add these fields to ChainInfo~~

**Comment by duguorong009** [comment]
@ma2bd 
Can you give more details?
I'd like to pick up the issue.

**Comment by duguorong009** [comment]
@ma2bd 
Can you take a look at the PR? 
In addition, do you have any update about `(TBD) Add these fields to ChainInfo`?

**Comment by ma2bd** [comment]
No, need to modify `ChainInfo`
