### ISSUE TITLE
Don't read from local storage just to filter notifications.

### ISSUE THREAD

**Issue by afck** [linera-io/linera-protocol#940]
If the tracker hasn't filtered out the `NewBlock` notification, that means the block in question hasn't been downloaded yet. Ideally we'd check its hash when we download it, instead of reading it again from storage afterwards.

**Comment by ma2bd** [comment]
@afck After #982, it seems that there is an opportunity to rethink `ChainClient::listen` as the sum of two distinct features:
* a synchronization process where notifications from validators are used to synchronized (chains of interest in) the local node with missing blocks (and maybe validation certificates and timeouts?)
* a listener to the local node

This way, the notifications served to the user will reflect the view of the local node by construction (no need to check certificate hashes for instance).
