### ISSUE TITLE
Remove is_err() from linera-core/src/unit_tests/worker_tests.rs

### ISSUE THREAD

**Issue by ma2bd** [linera-io/linera-protocol#987]
The goal of this cleanup task is to replace `is_err` by `assert!(matches!(...))` as we did in `linera-core/src/unit_tests/client_tests.rs` already.

**Comment by ashu26jha** [comment]
I did a little bit of digging and here is my findings. I found total of `14` instances of `is_err()`. Below is my finding (errors previously defined) on how to perform the cleanup (Just a rough mapping for discussing)

1.  Bad Signature                                -> `InvalidSignature`
2. Non Positive Amount                    -> `InsufficientFunding`
3. Timestamp too far in the future   -> `InvalidTimestamp`
4. Timestamp older than previous  -> `InvalidBlockTimestamp`
5. Missing earlier blocks                   -> `MissingEarlierBlocks`
6. Insufficient funding -> `InsufficientFunding`
7. Exceed Balance -> `InsufficientBalance`
8. Sender is checked -> `InvalidSigner(Owner)`
9. certificate_unknown_sender -> `CertificateSignatureVerificationFailed`
10. Unknown Sender -> `UnexpectedMessage`
11. With Chaining -> Couldn't find any 
12. admin chain has an anticipated message -> Couldn't find any 

I couldn't get hold of the point 11, function name is `run_test_handle_block_proposal_with_chaining`. Is ordering the reason?

Also I couldn't understand this comment `admin chain has an anticipated message`

Thank you!

**Comment by ma2bd** [comment]
Hi @ashu26jha, Thanks for inquiring. The methodology here is to figure out each expected error by executing the test: typically replacing each `assert!(xxxxx.is_err());` by `xxxxx.unwrap();` successfully.

**Comment by ashu26jha** [comment]
Hey thanks for the reply @ma2bd 
Just to be sure, here is an example of what I'm planning to do :

Previous :
```
// Insufficient funding

assert!(worker.handle_block_proposal(block_proposal).await.is_err());
```

Now :

```
// Insufficient funding

assert!(matches!(worker
      .handle_block_proposal(block_proposal).await,
      Err(SystemExecutionError::InsufficientFunding { .. })
));
```
Is this the way to move forward?

**Comment by ma2bd** [comment]
Yes, look at the examples in `client_test.rs` to be sure.
